'''测试numpy'''
import sys
# a = np.array([2,4,6,8,10,1,3,7,5])
# print(a)
# print(a[::-1])
# # print(a[7:2:-1])
# print(a.shape,a.dtype)
# print(type(a))
# b = np.arange(12).reshape(3,4)
# print(b)
# print(b.T)
# c = b.flatten()
# print(c)
# a = np.linspace(0,100,101,retstep=True)
# print(a)
# a = np.arange(12).reshape(2,2,3)
# print(a)
# b = a.transpose()
# print(b)
# print(a)
# a = np.random.randn(2,3)
# print(a)
# print(a.shape)
# x = np.ones((100,100))
# print(x)
# x[99,99] = 100
# print(x)
# print(x[[98,99],[98,99]])
print(sys.path)